### ISSUE TITLE
Can't create [plaits~] on Apple M1 Pro

### ISSUE THREAD

**Issue by wkc1986** [porres/pd-else#1556] opened 2023-03-07 20:19 UTC
Error:

`/Users/wkc/Documents/Pd/externals/else/plaits~.d_arm64: dlopen(/Users/wkc/Documents/Pd/externals/else/plaits~.d_arm64, 0x000A): tried: '/Users/wkc/Documents/Pd/externals/else/plaits~.d_arm64' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`

macOS 12.6.3
Pd 0.53-2test1-1-gfc20fc20

**Comment by esaruoho** [comment] 2023-03-12 21:33
@wkc1986 it seems like the plaits~ is then written to be x86 / intelmac instead of arm. did you try to build it yourself, or is this the package available from deken?

**Comment by wkc1986** [comment] 2023-03-13 21:57
`sfont~` is fine. `plaits~` issue is with Deken version. [[plaits~](https://github.com/porres/pd-else/tree/master/plaits%7E)/[pd-lib-builder](https://github.com/porres/pd-else/tree/master/plaits%7E/pd-lib-builder)/Makefile.pdlibbuilder](https://github.com/porres/pd-else/blob/master/plaits%7E/pd-lib-builder/Makefile.pdlibbuilder) didn't have a way to deal when `system` was `Darwin` and `target.arch` was `arm64`. I added these lines after line 582:

```
ifeq ($(target.arch), arm64)
    arch := $(target.arch)
    version.flag ?= -mmacosx-version-min=11.0
endif
```

This compiles and I can get audio from the newly built `plaits~.pd_darwin`.

**Comment by esaruoho** [comment] 2023-04-01 20:37
same results with M1

```
/Users/esaruoho/Library/Mobile Documents/com~apple~CloudDocs/pd/externals/else/plaits~.d_arm64: dlopen(/Users/esaruoho/Library/Mobile Documents/com~apple~CloudDocs/pd/externals/else/plaits~.d_arm64, 0x000A): tried: '/Users/esaruoho/Library/Mobile Documents/com~apple~CloudDocs/pd/externals/else/plaits~.d_arm64' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/esaruoho/Library/Mobile Documents/com~apple~CloudDocs/pd/externals/else/plaits~.d_arm64' (no such file), '/Users/esaruoho/Library/Mobile Documents/com~apple~CloudDocs/pd/externals/else/plaits~.d_arm64' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by porres** [comment] 2023-05-04 09:08
ok, did this in [d982a13](https://github.com/porres/pd-else/commit/d982a134deac05c632819aa8f3729c4579815c4d) will try to compile and please test if my build works

**Comment by porres** [comment] 2023-05-11 20:24
can you people confirm this is good with the rc8 test upload to deken?

**Comment by wkc1986** [comment] 2023-05-11 21:14
Unfortunately the Deken version still gets the error `/Users/wkc/Documents/Pd/externals/else/plaits~.d_arm64: dlopen(/Users/wkc/Documents/Pd/externals/else/plaits~.d_arm64, 0x000A): tried: '/Users/wkc/Documents/Pd/externals/else/plaits~.d_arm64' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`.

**Comment by porres** [comment] 2023-05-11 21:25
but i fixed it in https://github.com/porres/pd-else/issues/1556#issuecomment-1534359656 what am i missing? Also, related to this is https://github.com/porres/pd-else/issues/1640#issuecomment-1544672923

**Comment by wkc1986** [comment] 2023-05-11 22:06
I'm not sure. Just now I forked the current repository, compiled `plaits~` from the top-level `pd-else` folder and it worked fine:

```
make plaits pdincludepath=/Users/wkc/code/pd-0.53-2/src
make plaits-install objectsdir=/Users/wkc/code/wkc1986-else-build
```

This created a `plaits~.pd_darwin` in `/Users/wkc/code/wkc1986-else-build/else/`. I created `[declare -path /Users/wkc/code/wkc1986-else-build/else]` and then `[plaits~]` and it worked. So whatever's here on Github seems to be fine, I don't know what's the deal with the Deken version. 

The error message I posted above indicates it's still trying to load a `plaits~.d_arm64`, so maybe it didn't actually recompile for rc8? Indeed there is no `plaits~.pd_darwin` in the folder from Deken.

**Comment by porres** [comment] 2023-05-12 02:20
> The error message I posted above indicates it's still trying to load a plaits~.d_arm64, so maybe it didn't actually recompile for rc8? 

the rc8 test has plaits~.d_arm64, I didn't compile a plaits~.pd_darwin, but plaits~.d_arm64 for M1 and plaits~.m_amd64 for intel...

**Comment by porres** [comment] 2023-05-12 02:29
I dont have an M1 mac, so I can't test, and if I do "make plaits" without specifying the architecture I get a plaits~.pd_darwin that works for intel, not M1! So I have to do **make plaits-install objectsdir=$(pwd)/.. arch="arm64" extension=d_arm64**  to get the M1 version. This is what I did for the rc8 upload...

for the other objects I have a fat binary... now I am trying to build a fat binary for plaits as well. It should work since all the other ELSE objects also work right?

This is what I did... **make plaits-install objectsdir=../ arch="arm64 x86_64" extension=d_fat**

here's the binary --> 
[plaits~.d_fat.zip](https://github.com/porres/pd-else/files/11458339/plaits.d_fat.zip)
 does it work for you? Can you try and compile a fat binary and send me so I can test if it doesn't work?

**Comment by wkc1986** [comment] 2023-05-12 02:40
Away from computer so I can’t test right now, but looks like the target.arch variable comes from build.arch which comes from uname, meaning the way I modified the Makefile.pdlibbuilder might not allow for cross-compilation. It worked for me since I’m on M1. Will investigate later.On May 11, 2023, at 22:30, porres ***@***.***> wrote:﻿
I dont have an M1 mac, so I can't test, and if I do "make plaits" without specifying the architecture I get a plaits~.pd_darwin that works for intel, not M1! So I have to do make plaits-install objectsdir=$(pwd)/.. arch="arm64" extension=d_arm64  to get the M1 version. This is what I did for the rc8 upload...
for the other objects I have a fat binary... now I am trying to build a fat binary for plaits as well. It should work since all the other ELSE objects also work right?
This is what I did... make plaits-install objectsdir=../ arch="arm64 x86_64" extension=d_fat
here's the binary -->
plaits~.d_fat.zip
does it work for you? Can you try and compile a fat binary and send me so I can test if it doesn't work?

**Comment by porres** [comment] 2023-05-12 04:13
> Away from computer so I can’t test right now,

ok, test it when you can that fat binary

> the way I modified the Makefile.pdlibbuilder might not allow for cross-compilation.

then I should probably revert back, and in fact we now have an update to it by @charlesneimog who upgraded it to 0.6.0... weird thing is that I tried using that for a while and it didn't work, can't remember what it was but can find it back

thing is that now I don't see any issue and tried yet another fat binary, see if this one works --> 
[plaits~.d_fat.zip](https://github.com/porres/pd-else/files/11458817/plaits.d_fat.zip)

**Comment by wkc1986** [comment] 2023-05-12 19:15
The `plaits~.d_fat` doesn't work:

```
/Users/wkc/Downloads/plaits~.d_fat: dlopen(/Users/wkc/Downloads/plaits~.d_fat, 0x000A): tried: '/Users/wkc/Downloads/plaits~.d_fat' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

This looks like if you tell it to compile a `.d_fat` it builds for Intel:

```
  ifeq ($(extension), d_fat)
    arch := i386 x86_64
```

I modified that to include arm64:

```
    arch := i386 x86_64 arm64
```

but with the current repo I can't compile:

```
wkc@venice plaits~ % make pdincludepath=/Users/wkc/code/pd-0.53-2/src
++++ info: using Makefile.pdlibbuilder version 0.6.0
++++ info: using Pd API /Users/wkc/code/pd-0.53-2/src/m_pd.h
++++ info: making target all in lib plaits~
++++ info: evaluating implicit prerequisites in lib plaits~.....
clang: error: no such file or directory: 'plaits/dsp/engine/chord_engine.cc '
clang: error: no input files
pd-lib-builder//Makefile.pdlibbuilder:1013: *** missing separator.  Stop.
```

This seemed to be due to some non-space whitespaces in `plaits~/Makefile`. After changing those to spaces I could compile. 

```
wkc@venice wkc1986-pd-else % make plaits pdincludepath=/Users/wkc/code/pd-0.53-2/src extension=d_fat
++++ info: using Makefile.pdlibbuilder version 0.6.0
++++ info: making target plaits in lib else
/Library/Developer/CommandLineTools/usr/bin/make -C plaits~ arch=""
++++ info: using Makefile.pdlibbuilder version 0.6.0
++++ info: using Pd API /Users/wkc/code/pd-0.53-2/src/m_pd.h
++++ info: making target all in lib plaits~
++++ info: evaluating implicit prerequisites in lib plaits~.....
++++ info: linking objects in plaits~.d_fat for lib plaits~
c++ -undefined suppress -flat_namespace -bundle   -mmacosx-version-min=10.9  -o plaits~.d_fat plaits~.o stmlib/dsp/units.o stmlib/utils/random.o stmlib/dsp/atan.o plaits/dsp/voice.o plaits/dsp/engine/additive_engine.o plaits/dsp/engine/bass_drum_engine.o plaits/dsp/engine/chord_engine.o plaits/dsp/engine/fm_engine.o plaits/dsp/engine/grain_engine.o plaits/dsp/engine/hi_hat_engine.o plaits/dsp/engine/modal_engine.o plaits/dsp/engine/noise_engine.o plaits/dsp/engine/particle_engine.o plaits/dsp/engine/snare_drum_engine.o plaits/dsp/engine/speech_engine.o plaits/dsp/engine/string_engine.o plaits/dsp/engine/swarm_engine.o plaits/dsp/engine/virtual_analog_engine.o plaits/dsp/engine/waveshaping_engine.o plaits/dsp/engine/wavetable_engine.o plaits/dsp/speech/lpc_speech_synth.o plaits/dsp/speech/lpc_speech_synth_controller.o plaits/dsp/speech/lpc_speech_synth_phonemes.o plaits/dsp/speech/lpc_speech_synth_words.o plaits/dsp/speech/naive_speech_synth.o plaits/dsp/speech/sam_speech_synth.o plaits/dsp/physical_modelling/modal_voice.o plaits/dsp/physical_modelling/resonator.o plaits/dsp/physical_modelling/pm_string.o plaits/dsp/physical_modelling/string_voice.o plaits/resources.o -lc   
++++info: target all in lib plaits~ completed
wkc@venice wkc1986-pd-else % make plaits-install objectsdir=../wkc1986-else-build/ extension=d_fat
++++ info: using Makefile.pdlibbuilder version 0.6.0
++++ info: making target plaits-install in lib else
/Library/Developer/CommandLineTools/usr/bin/make -C plaits~ install installpath="../wkc1986-else-build//else" arch=""
++++ info: using Makefile.pdlibbuilder version 0.6.0
++++ info: making target install in lib plaits~
++++ info: installpath is '../wkc1986-else-build//else'
++++info: target all in lib plaits~ completed
++++ info: executables of lib plaits~ installed from /Users/wkc/code/wkc1986-pd-else/plaits~ to ../wkc1986-else-build//else
install -m 755 -d -v "../wkc1986-else-build//else"
install -p -m 644 'plaits~.d_fat' "../wkc1986-else-build//else";
```

This creates a `plaits~.d_fat` in the build directory that works on my M1. File is attached; hopefully it works on your Intel Mac?
[plaits~.d_fat.zip](https://github.com/porres/pd-else/files/11467053/plaits.d_fat.zip)

**Comment by porres** [comment] 2023-05-12 19:35
none of the both I gave you work? how come other objects that I compile like this do work? Can you send me a PR with your modification?

**Comment by porres** [comment] 2023-05-12 19:36
the binary you sent doesn't seem to work for me, it gives me "load_object: Symbol "plaits_tilde_setup" not found"

**Comment by wkc1986** [comment] 2023-05-12 19:48
Yeah, I couldn't get your d_fats to work, from the error messages they were x86_64 only.

Unfortunately I don't have a way right now to test whether externals compiled on my M1 will work on Intel Mac. In any case I submitted the PR.

**Comment by porres** [comment] 2023-05-15 17:42
It seems someone tested and it didn't work...

**/Users/macbookm1/Documents/Pd/externals/else/plaits~.d_fat: dlopen(/Users/macbookm1/Documents/Pd/externals/else/plaits~.d_fat, 10): no suitable image found.  Did find:
 /Users/macbookm1/Documents/Pd/externals/else/plaits~.d_fat: mach-o, but wrong architecture
 /Users/macbookm1/Documents/Pd/externals/else/plaits~.d_fat: mach-o, but wrong architecture
plaits~
... couldn't create**

at this point I am just asking you to send me an M1 binary so I can upload an update... and we'll keep investigating this...

**Comment by porres** [comment] 2023-05-15 23:48
yet another binary to test 
[plaits~.d_fat.zip](https://github.com/porres/pd-else/files/11482677/plaits.d_fat.zip)

**Comment by porres** [comment] 2023-05-15 23:50
> yet another binary to test
> [plaits~.d_fat.zip](https://github.com/porres/pd-else/files/11482677/plaits.d_fat.zip)

a student of mine confirmed this one works, so I'm releasing an update and uploading it to deken. Please also confirm this one works so I can close this

**Comment by wkc1986** [comment] 2023-05-16 18:49
These last two binaries worked. What changed?

**Comment by porres** [comment] 2023-05-16 18:56
> What changed?

changed the pdlibbuilder to the same I'm using in ELSE (which is 0.6.0), have fun with the latest upload to deken then

**Closed by porres** 2023-05-16 18:56 UTC
Labels: For Next Release
