### ISSUE TITLE
else/note displays strange characters if -note -size flags are used in different order

### ISSUE THREAD

**Issue by muziker** [porres/pd-else#659] opened 2020-01-31 09:05 UTC
If you do this [else/note -note A -size 8] and put that in a graph on parent, there are extra characters that appear. If you do this [else/note -size 8 -note A], this does not happen

**Comment by porres** [comment] 2020-01-31 21:10
can you please send me an example and screenshots? I'm not always on the computer

**Comment by muziker** [comment] 2020-02-02 10:57
Create a [else/note -note A -size 8], create [else/note -size 8 -note B]. Turn on graph-on-parent, and put the patch into a main patch. You'll see a bunch of extra 1/0s for A but none for B.

**Comment by porres** [comment] 2020-02-02 16:35
well, I was fine with the instructions/description, I just asked for an example patch

**Comment by porres** [comment] 2020-02-04 21:42
so, I finally got to a computer to test this and I can't reproduce... and since I have no test patch, I'll have to close this.

Anyway, I'm redesigning cyclone's comment from scratch and the new note update will be based on it as a variant, so... maybe wait for an update of cyclone and note to see if there are still issues, and please try to provide a test patch when you're reporting a bug.

thanks

**Closed by porres** 2020-02-04 21:42 UTC
