### ISSUE TITLE
Crash on Copy / Paste with "envgen~" Object

### ISSUE THREAD

**Issue by EdLud** [porres/pd-else#807] opened 2020-10-04 09:34 UTC
When trying to copy/paste (Osc~) and (else/envgen~ 50 1 50 0.5 200 0 -suspoint 2 -exp -0.25 -0.5 -1 -0.5), both connected to an (*~) object, pure data crashes to desktop.

**Comment by porres** [comment] 2020-10-04 16:04
can you provide me with a test patch? zip it and upload it here on github

**Comment by porres** [comment] 2020-10-04 16:10
> can you provide me with a test patch? zip it and upload it here on github

I cannot reproduce this error on my machine, so I suspect this error is not really happening and I'm closing this. You have to provide me with a patch that I can see the error happening and give more details on your system so we can reopen this.

**Comment by EdLud** [comment] 2020-10-04 18:21
Running 
MacOS 10.12.6 
Pd 0.51.1
else 1.0 beta 31
[envgen~_error_testpatch.pd.zip](https://github.com/porres/pd-else/files/5324028/envgen._error_testpatch.pd.zip)

**Comment by porres** [comment] 2020-10-04 18:38
Works for me... damn...

MacOS 10.14.6 (although I doubt it matters if it's an older one like 10.12)
Pd 0.51-2 (not the 32 bit version)
else 1.0 beta 31 (compatible with the above Pd architecture, downloaded directly via Pd).

That's what you're using, right?

I'm afraid I can't help you if so... cause it's just too weird. Is it only happening with envgen~?

**Comment by porres** [comment] 2020-10-04 18:39
what if you create a new envgen~ without duplicating, what happens?

**Comment by porres** [comment] 2020-10-04 20:32
we can also try bringing this to the Pd list or something, maybe others can help figuring what could be wrong

**Comment by EdLud** [comment] 2020-10-04 21:56
i don't get the crash when i'm not using the start up flags for  (envgen~), so i guess it's a problem with that
so just
(envgen~ 50 1 50 0.5 200 0)
instead of (envgen~ 50 1 50 0.5 200 0 -suspoint 2 -exp -0.25 -0.5 -1 -0.5)
can be duplicated

**Comment by porres** [comment] 2020-10-05 00:49
ok, that gives me something to work with I guess. I could look and see if I can make some changes (if any) about the flags. Though it's still quite weird to me...

**Comment by porres** [comment] 2020-10-05 17:49
well, I have nothing looking at the code, so far...

what happens if you just create a new [envgen~] object with flags?

btw, you do have the 64 bit (regular) version, right? It just bothers me that I can't replicate this... so...

**Comment by porres** [comment] 2022-04-21 02:44
I am closing this as I think this has been fixed in the last update, please try @EdLud and if you try and still find the issue, please reopen!!!

**Closed by porres** 2022-04-21 02:44 UTC
