### ISSUE TITLE
else/pad doesn't send click 0 messages when behind canvas

### ISSUE THREAD

**Issue by jyg** [porres/pd-else#1459] opened 2023-01-31 14:39 UTC
I need to intercept mouse messages behind a canvas. When I use else/pad, it doesn't output "click 0" messages when there is a canvas in foreground.
![image](https://user-images.githubusercontent.com/1431894/215790632-c53c6ff8-e08c-4b15-834e-d7799a364717.png)
pd vanilla 0.53.0,  linux

**Comment by porres** [comment] 2023-01-31 15:00
Upload a patch please

**Comment by porres** [comment] 2023-01-31 19:53
duplicate of https://github.com/porres/pd-else/issues/918

**Closed by porres** 2023-01-31 19:53 UTC
