### ISSUE TITLE
numbox~ receive + send parameters (so that can get rid of the black lines at the top left and bottom left corners

### ISSUE THREAD

**Issue by esaruoho** [porres/pd-else#1593] opened 2023-04-01 20:35 UTC
i'm not seeing a method of setting receive + send parameters / attributes for numbox~ - i'm currently on a spree to get rid of all those black lines from the top left and bottom left corner of all objects i'm using (in case i can use them with s / s~ and r / r~
<img width="476" alt="Screenshot 2023-04-01 at 23 33 24" src="https://user-images.githubusercontent.com/4966687/229312863-933535b2-bdfc-4549-9efb-3753332e02b7.png">

**Comment by porres** [comment] 2023-04-02 14:17
duplicate of https://github.com/porres/pd-else/issues/1588

**Closed by porres** 2023-04-02 14:17 UTC

**Comment by esaruoho** [comment] 2023-04-03 07:17
@porres your ticket only talks about adding receive symbol, not send symbol.
now, if that's shorthand for "add both receive + send" then fine, let this ticket stay closed.
