### ISSUE TITLE
plaits is sometimes muted when duplicated

### ISSUE THREAD

**Issue by tomara-x** [porres/pd-else#1589] opened 2023-03-29 23:26 UTC
open this patch, click the bangs, the one to the left and middle one work fine. if the one to the right works, close the patch and reopen it, and keep going. sometimes you'll hear a click when loading the patch and if you then try the bang of the right plaits, you'll find that it doesn't produce any sound

(edit: if it does work, you can try duplicating the right plaits with all its connections and connecting it to dac)

[plaits-debug.pd.txt](https://github.com/porres/pd-else/files/11106340/plaits-debug.pd.txt)

i have a video of it happening in plugdata, but it's still the same in vanilla: (this has audio)

https://user-images.githubusercontent.com/86204514/228689390-4f1b008b-c1d2-4f4a-a2e6-7ab6823b3f39.mp4  

  .
it was very sneaky just to catch it, so i hope it doesn't give you much trouble :heart:

**Comment by porres** [comment] 2023-03-30 16:56
can't reproduce it :/. but haven't tested in plugdata

**Comment by tomara-x** [comment] 2023-03-30 17:06
in vanilla it's a 50/50 chance, in plugdata it always happens
but in vanilla if i try duplicating a plaits and changing the mode it's much more likely to happen. the only difference i can think of is that plugdata runs with pulseaudio and vanilla runs with jack.. could it be a linux exclusive?

**Comment by porres** [comment] 2023-03-30 17:13
hmmmm, never happens on my mac no :/

**Comment by porres** [comment] 2023-03-30 17:15
ok, got it to happen by duplicating

**Comment by porres** [comment] 2023-03-30 17:16
> ok, got it to happen by duplicating

well, not really, thing is that the object might not get initialized when duplicated

**Comment by porres** [comment] 2023-03-30 17:22
i guess accidents might happen when duplicating the object with getting information from the number boxes, but it always initializes correctly when reopening the patch (again, vanilla/mac)

**Comment by tomara-x** [comment] 2023-03-30 18:46
how though? like, all the numboxes have init enabled, so why wouldn't that work?
when you did get it to happen what was it like? it's outputting -1 on both signal outlets, but for some reason the vocal synth (model 7) works fine! so weird

**Comment by porres** [comment] 2023-03-30 19:02
I was testing model 8, sometimes duplicating it gets ruined, but it works fine if reinitialized properly or when reloading the patch

**Comment by porres** [comment] 2023-03-30 19:02
not really sure what to do here :(

**Comment by tomara-x** [comment] 2023-03-30 19:18
huh, so it needs to be recreated and then it works
don't worry about it if it can't be fixed <3

**Comment by porres** [comment] 2023-03-30 19:35
yeah, unless there's a problem when creating the patch, I don't know what to do :/ if you recreate it then it works fine? If so, I guess I'll just close this...

**Comment by tomara-x** [comment] 2023-03-30 19:51
yeah, it's just like you said, when it gets messed up, i then delete that plaits object and create another and it works. would be really nice if there was a way to make sure it does initialize properly when duplicated, but i'm assuming you've already thought of that
so yeah, take care

**Closed** 2023-03-30 19:53 UTC

**Comment by tomara-x** [comment] 2023-03-31 17:21
it never happens with this
[plait-debug-10.pd.txt](https://github.com/porres/pd-else/files/11124363/plait-debug-10.pd.txt)
but with a high morph, like this, it does happen
[plait-debug-9.pd.txt](https://github.com/porres/pd-else/files/11124369/plait-debug-9.pd.txt)
still have no clue why

**Comment by porres** [comment] 2023-03-31 18:02
you can just upload zipped patches here

**Comment by tomara-x** [comment] 2023-04-02 17:33
today's update: managed to isolate it, so it happens even without any methods at init time, just creation arguments with plaits (again, model 8 and high morph)
and also someone on the plugdata discord was kind enough to do a test on windows and confirmed that it happens there too

[plait-debug-9-8.pd.zip](https://github.com/porres/pd-else/files/11132879/plait-debug-9-8.pd.zip)
(out~ has dcblock! that's cool, i didn't know that!)

**Comment by tomara-x** [comment] 2023-04-02 17:35
maybe keep this open? since it seems like it is an unsolved issue

**Comment by porres** [comment] 2023-04-03 00:44
> [plait-debug-9-8.pd.zip](https://github.com/porres/pd-else/files/11132879/plait-debug-9-8.pd.zip)

works fine here... what happens for you?

does the patch need all of these copies?

if the issue is clear and model 8 with high morph doesn't work for you, we can open a new issue...

**Comment by tomara-x** [comment] 2023-04-03 00:49
some of them are frozen outputting -1 dc

the copies are to increase the chances of it happening (since it screams undefined behavior)

why open a new issue? it's the same problem, and the info here describe it

**Comment by tomara-x** [comment] 2023-04-03 00:50
idk why for some reason it doesn't happen on mac, it's a very weird bug

**Comment by porres** [comment] 2023-04-03 00:52
> why open a new issue? it's the same problem,

I think it's a more narrowed down issue, and quite different than the original (which involved duplicating the file). It is also a valid issue that we can't ignore... and we already too much unnecessary information here, it just feels like a good reboot

**Comment by tomara-x** [comment] 2023-04-03 00:58
cool cool, in a sec
