### ISSUE TITLE
[pvoc.freeze~] 

### ISSUE THREAD

**Issue by bazilmuzik** [porres/pd-else#503] opened 2019-05-18 12:18 UTC
Connections missing (v1.0 beta 20, Windows releases) :

- in the first patch with the [xfade~] object
- in the [norm] subpatch of [phase_accum] with the two [mag~] objects
- maybe elsewhere also

Replacing it with the [pvoc.freeze~] instance from the Source Code .zip folder fixed everything (on my computer).

**Comment by porres** [comment] 2019-05-18 16:04
can't reproduce this, I downloaded both windows versions from https://github.com/porres/pd-else/releases/tag/v1.0-beta20 and the abstractions were fine and working. 

Ok, I did this on my mac machine, but it doesn't make sense that the files are corrupted if I open them in windows.

Can you reboot your procedure and try to see if you can replicate it yourself with all possible details? Then I can try and see if I can replicate it as well?

If you cannot replicate this again, please close the issue

**Comment by bazilmuzik** [comment] 2019-05-20 18:43
Hello ! Sorry for the late response, I wasn't home these days.

I retried everything from scratch and it went all right with Pd vanilla. Then I installed Purr Data, and there was an error message with this object, as if it wasn't able to load everything from the else library... I guess what I did the other day was to save unintentionally this error within the [pvoc.freeze~] patch. When Pd doesn't find an object, it tries to maintain the connections as there were, but in this case, no (hence the missing connections I got after all). I think I forgot to delete every externals the other day before reinstalling Pd and Purr, that's why the error was still there.

So after all, it has nothing to do with your release, it was only a problem of bad externals managing from me, I will close the report on Github !

Again, thank you a lot for your all you're doing for this programm and its users 🙂

Have a nice day


________________________________
De : Alexandre Torres Porres <notifications@github.com>
Envoyé : samedi, 18 mai 2019 18:04
À : porres/pd-else
Cc : bazilmuzik; Author
Objet : Re: [porres/pd-else] [pvoc.freeze~] (#503)


can't reproduce this, I downloaded both windows versions from https://github.com/porres/pd-else/releases/tag/v1.0-beta20 and the abstractions were fine and working.

Ok, I did this on my mac machine, but it doesn't make sense that the files are corrupted if I open them in windows.

Can you reboot your procedure and try to see if you can replicate it yourself with all possible details? Then I can try and see if I can replicate it as well?

If you cannot replicate this again, please close the issue

**Closed** 2019-05-20 18:44 UTC

**Comment by porres** [comment] 2019-05-20 19:18
well, in the end it's then another example of how Purr Data is incompatible. But I wouldn't know why... anyway, I stopped caring about Purr Data when I realized it had all these issues :(

**Comment by bazilmuzik** [comment] 2019-05-21 11:46
Yes, after these problems, I consider only using Purr Data to have a look at the many libraries it imports and see if there are interesting objects for me... and install them in vanilla !
