### ISSUE TITLE
slider2d does not work when inside a GOP

### ISSUE THREAD

**Issue by fdch** [porres/pd-else#670] opened 2020-03-23 00:25 UTC
Hi Alex, 

Just found out that inside GOP using windows [slider2d] does not take mouse interaction. On macos there's no issue and I can use it inside a GOP. I tested the windows side using miller's latest windows .exe binary. It might be a tcl/tk thing, but I have no time to look deeper into this. 

BTW: great abstraction. Could you make it all vanilla? And, an iemgui like yours would be a nice addition to vanilla altogether, more than the knob thingy ;)

**Comment by porres** [comment] 2020-03-23 00:45
> using miller's latest windows .exe binary

Pd 0.50-2?

**Comment by porres** [comment] 2020-03-23 00:47
> Could you make it all vanilla?

not yet, it depends on mouse interactions that vanilla does not have a way for (yet). I have a plan to suggest a hack, but it needs first a PR that is waiting in line

> And, an iemgui like yours would be a nice addition to vanilla altogether

Agreed, but I wouldn't know how to make it a compiled object yet.

**Comment by porres** [comment] 2020-03-23 00:48
> And, an iemgui like yours would be a nice addition to vanilla altogether

why dont you open a request? :)

**Comment by porres** [comment] 2020-03-23 00:49
> Just found out that inside GOP using windows [slider2d] does not take mouse interaction

mouse interactions are provided by the [else/canvas.mouse] object... I'll test it soon, eventually, but maybe you can do that too...

**Comment by fdch** [comment] 2020-03-23 01:07
oh, i thought you were just routing a click from [struct]
> mouse interactions are provided by the [else/canvas.mouse] object... I'll test it soon, eventually, but maybe you can do that too...
> 
yes, i'll give it a try when I have some time

**Comment by porres** [comment] 2020-04-06 21:32
I finally tested on windows and confirmed this...

Now, I also see this happens on macOS, so it's not an OS related bug.

And I see now what the problem is and have to think about it...

**Comment by porres** [comment] 2020-04-06 22:36
closing in favor of https://github.com/porres/pd-else/issues/672

**Comment by fdch** [comment] 2020-04-06 23:57
well, it did not happen (to me) on macos, which is why I said this happened on windows. But I compiled myself and I did not test with miller's binary

**Comment by porres** [comment] 2020-04-07 00:42
yeah, it's weird it didn't happen to you...

btw, I also compiled myself with miller's binary

if in fact you don't see this happening on macOS, I'd really like to know!!!!!!!!!!!!!

**Comment by porres** [comment] 2020-04-14 00:13
an elegant solution is not possible, it would require a new GUI that is transparent, something like this https://github.com/porres/pd-else/issues/674

but I'm going for a dirty hack for the moment

**Closed** 2020-04-14 00:14 UTC
Labels: For Next Release, PRIORITY, bug

**Comment by porres** [comment] 2020-04-14 00:15
note that this only works for a graph on parent of one level, for now, I could add a couple more, but it's just gonna be uglier...

**Comment by porres** [comment] 2020-04-14 00:15
I might add at least one other level... let's see

**Comment by fdch** [comment] 2020-04-14 00:25
on macos i tried with multiple sublevels (i think two, but i'll share the patch when i am on my computer) and it worked. i am using tk 8.6.9


fdch.github.io

**Comment by porres** [comment] 2020-04-14 00:26
have you tried the commit I just made?

**Comment by fdch** [comment] 2020-04-14 00:28
nope, else from deken. i can try but later this week


fdch.github.io

**Comment by fdch** [comment] 2020-04-14 00:31
i am not sure if you'll be able to see the vid, i am sending it via email. it's 3 levels i believe


fdch.github.io

**Comment by porres** [comment] 2020-04-14 00:36
well, for me, else from deken doesn't work in any GOP, for windows, mac or linux... 

I just made a fix, but it works only for 1 level above... 

please test

**Comment by fdch** [comment] 2020-04-14 01:08
This is the patch that works on macos, else from deken, pd compiled with Tk 8.6.9
```
#N struct 1005-point float x0 float y0 float s;
#N canvas 544 95 450 300 12;
#N canvas 0 22 450 300 (subpatch) 0;
#N canvas 0 22 450 300 (subpatch) 0;
#X obj 106 105 else/slider2d;
#X coords 0 -1 1 1 151 147 1 100 100;
#X restore 104 105 pd;
#X coords 0 -1 1 1 177 162 1 100 100;
#X restore 91 89 pd;
```

**Comment by fdch** [comment] 2020-04-14 01:17
NOTE: I just tried with the latest pd-else git, and that same patch works fine. I can't try that for windows, though, I'll have to wait for the binary.

**Comment by porres** [comment] 2020-04-14 01:32
we have to seriously talk about this, because it is impossible things work in macos with the deken version...

**Comment by fdch** [comment] 2020-04-14 01:33
ok, let me double check and remove the else i have and download again from deken.


fdch.github.io

**Comment by fdch** [comment] 2020-04-14 01:38
I am getting else version 
```
else[v1.0beta27](Darwin-amd64-32).dek
	Uploaded by porres @ 2020-02-05 22:35:34
```
And you are *right*, it does not work from deken.
How do I check the else version I had before? I must have compiled it sometime and I forgot! Sorry for the noise!!

**Comment by porres** [comment] 2020-04-14 01:44
> How do I check the else version I had before? 

No idea, but I bet you had an older version of slider2d that relied on data structures, not [canvas.mouse]

and I needed something like [canvas.mouse] so the GUI could behave in a non "jump on click" mode

**Comment by fdch** [comment] 2020-04-14 01:45
Two comments here:

I now have 3 versions of else (1. deken, 2. compiled-old, 3. compiled-latest)

"2.compiled-old" supports 3 levels of subpatch without any issue. Neither "1.deken" nor "3.compiled-latest" allow this to happen.

Second
"2.compiled-old" works like "jump on click" iemgui sliders... "1.deken" and "2.compiled-latest" both move like "steady on click"

(I just saw your jump-on-click comment)

**Comment by fdch** [comment] 2020-04-14 01:46
> > How do I check the else version I had before?
> 
> No idea, but I bet you had an older version of slider2d that relied on data structures, not [canvas.mouse]

the "2.compiled-old" version seems to be compiled on Apr 13 21:35, that's just date when the binaries I have were created.

**Comment by porres** [comment] 2020-04-14 01:48
README has the version info

**Comment by porres** [comment] 2020-04-14 01:49
but you know, vanilla should really have this, let's see first if the knob gets in first

**Comment by porres** [comment] 2020-04-14 01:51
not "this", but a 2 dimensional slider, as a proper compiled GUI

**Comment by porres** [comment] 2020-04-14 01:51
I also just requested a symbol GUI...

**Comment by fdch** [comment] 2020-04-14 02:07
i agree, like a knob, and a 2d radio matrix while we are at it :) 


fdch.github.io

**Comment by porres** [comment] 2020-04-14 02:13
how do you like else/mtx.ctl?

**Comment by fdch** [comment] 2020-04-14 02:18
wow, i did not see that! looks great. 

I'd vote, still, for an iemgui-like matrix. For example, here's something I did that could be extended to a 2d matrix, if you have time, give fd_lib/sradio a try (you can get fd_lib from deken, or from my git repo https://github.com/fdch/fd_lib). There's a discussion with Christof about this, I can't remember where.
