### ISSUE TITLE
Tcl invalid command name ":pdwindow::post" in [vocoder~] help patch

### ISSUE THREAD

**Issue by macumbista** [porres/pd-else#1345] opened 2022-09-12 14:04 UTC
MacOS version 10.15.7
Pure Data versions 0.51.4 and 0.52.2

Trying to open the help patch for [vocoder~] gives Tcl errors for the command ":pdwindow::post"

The errors appear slightly differently in each version of Pd.

0.51.4: Many lines which look like this:

(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::post"
    while executing
":pdwindow::post {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded

0.52.2: Here is the complete spew:

(Tcl) INVALID COMMAND NAME: invalid command name "307"
    while executing
"307 589 320 589"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) UNHANDLED ERROR: bad option "coords.x7fb344acdb20.c": must be addtag, bbox, bind, canvasx, canvasy, cget, configure, coords, create, dchars, delete, dtag, find, focus, gettags, icursor, imove, index, insert, itemcget, itemconfigure, lower, move, moveto, postscript, raise, rchars, scale, scan, select, type, xview, or yview
    while executing
".x7fb344acdb20.c coords.x7fb344acdb20.c coords 7fb32381ba00KNOB 287 652 300 652"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name "326"
    while executing
"326 632 339 632"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name "x7fb344acdb20.c"
    while executing
"x7fb344acdb20.c coordspdtk_ping"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ""
    while executing
""
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ""
    while executing
""
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name "ecting"
    while executing
"ecting -tags [list .x7fb34481f220.t7fb2e4144b40R obj]"
    ("uplevel" body line 113)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ""
    while executing
""
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ""
    while executing
""
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ""
    while executing
""
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ""
    while executing
""
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ""
    while executing
""
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ""
    while executing
""
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ""
    while executing
""
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"receive~ test: no matching send
expr~ divide by zero detected
expr~ divide by zero detected
expr~ divide by zero detected
(Tcl) INVALID COMMAND NAME: invalid command name "}"
    while executing
"}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name "d-Processing/5.Vocoder}"
    while executing
"d-Processing/5.Vocoder} {2.Vocoder.pd} {} 0::pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name "}"
    while executing
"}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name "d-Processing/5.Vocoder}"
    while executing
"d-Processing/5.Vocoder} {2.Vocoder.pd} {} 0::pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"receive~ test: no matching send
expr~ divide by zero detected
expr~ divide by zero detected
expr~ divide by zero detected
receive~ test: no matching send
expr~ divide by zero detected
expr~ divide by zero detected
expr~ divide by zero detected
 vocoder~
... couldn't create
can't resize to zero or negative number; setting to 1
receive~ test: no matching send
expr~ divide by zero detected
expr~ divide by zero detected
expr~ divide by zero detected
(Tcl) INVALID COMMAND NAME: invalid command name "sp"
    while executing
"sp OFF"
    ("uplevel" body line 16)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) INVALID COMMAND NAME: invalid command name ":pdwindow::logpost"
    while executing
":pdwindow::logpost .x0 4 {tried /Users/dh/Documents/Pd/externals/else/voice.wav and succeeded
}"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"(Tcl) UNHANDLED ERROR: bad window path name ".x7fb2e39d1160"
    while executing
"wm deiconify $mytoplevel"
    (procedure "pdtk_canvas_raise" line 2)
    invoked from within
"pdtk_canvas_raise .x7fb2e39d1160"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"

**Comment by porres** [comment] 2022-10-08 20:58
can't reproduce it, which ELSE version are you using?

**Comment by porres** [comment] 2022-10-18 01:22
please help me, otherwise I'll have to close this as unreproducible, can you test with the latest version of ELSE?

**Comment by macumbista** [comment] 2022-10-18 14:51
Installed latest else. Using Pd 0.52-2, Intel Mac 2,6 GHz 6-Core Intel Core i7, fresh restart. Opening vocoder~-help.pd gives:

(Tcl) INVALID COMMAND NAME: invalid command name "lin/db2lin.so"
    while executing
"lin/db2lin.so and failed"
    ("uplevel" body line 347)
    invoked from within
"uplevel #0 $docmds"

This error does not happen in Pd-0.51-4, which is the other installed version I have.

**Comment by porres** [comment] 2022-10-18 16:17
"while executing lin/db2lin.so"

this is weird as hell, there's an object in ELSE called [db2lin] but it is an abstraction, not a compiled object. This object is also not used in the help file of vocoder, neither in the vocoder~ abstraction. There is no db2lin.so file in ELSE, neither a 'lin' folder. The only .so files in ELSE are dendencies for sfont~

 I see no other option than not to consider this is an issue from ELSE, and I also cannot reproduce it, so I am closing it. Perhaps we can investigate what this error means by filing an issue in pd's repository, I never saw the error "uplevel #0 $docmds", I don't know what it means, maybe they can help.

**Closed by porres** 2022-10-18 16:17 UTC
