### ISSUE TITLE
1020 instances of [dir] crashes PD (Ubuntu)

### ISSUE THREAD

**Issue by LGoodacre** [porres/pd-else#248] opened 2018-05-27 19:56 UTC
On Ubuntu 18.04, 1020 instances of [dir] crash PD. If I have 1019 instances open, creating one more gives a "Segmentation fault (core dumped)" console message. See the file "1018dir.pd" and create two more instances of [dir] for an example.

(Bizarrely, I can't seem to save a file with 1019 instances of [dir] in it--the file simply refuses to save. Presumably this error is related).

If I call 1020 or more instances of [dir] within abstractions, I then can't open up any new abstractions. I either get a "can't create" message, or sometimes "too many open files", or even "can't load abstraction within itself". Open the file "clone-dir.pd" and then try to load a regular abstraction to see this.
 
This all seems very strange, but I'm describing it in as much detail as I can. Initial tests show that it works OK in Windows, though I have only tested it thoroughly on Ubuntu.

Using Else Beta 9 here.

Here are the test files I mentioned: https://1drv.ms/u/s!AvOKHMTdUCc2xFoXvWc4zsEmM3De

**Comment by LGoodacre** [comment] 2018-05-27 19:57
Here are the test files I mentioned: https://1drv.ms/u/s!AvOKHMTdUCc2xFoXvWc4zsEmM3De

**Comment by porres** [comment] 2018-05-27 21:03
> See the file "1018dir.pd" and create two more instances of [dir] for an example.

i cant even open that one, it crashes here

how about with that other object you were using before?

**Comment by LGoodacre** [comment] 2018-05-28 03:32
Exactly the same behavior with beta 7.

**Comment by porres** [comment] 2018-05-28 04:10
so it's none of the new things, and I have to redo it from scratch :)

**Comment by porres** [comment] 2018-06-10 21:16
hopefully fixed with this https://github.com/porres/pd-else/commit/e8f01e96789fbb020cfb5244e93038dde793c146

**Comment by LGoodacre** [comment] 2018-06-21 05:53
I'm still getting the same crash with beta 10...

**Comment by porres** [comment] 2018-06-21 06:37
not me in macOS... resend a test patch?

**Comment by LGoodacre** [comment] 2018-06-21 07:44
It's just the same as before: https://1drv.ms/u/s!AvOKHMTdUCc2xFoXvWc4zsEmM3De

Is it possible that I'm still accessing the old version of [dir] for some reason? When I call the helpfile it is definitely located in the folder where beta 10 is downloaded, suggesting that it's in the right place...

**Comment by LGoodacre** [comment] 2018-06-21 07:46
What I mean is: maybe the Linux version that you uploaded to Deken accidentally included the wrong version of [dir] ??

**Comment by porres** [comment] 2018-06-21 18:42
> maybe the Linux version that you uploaded to Deken accidentally included the wrong version of [dir] ?

not a chance, and now I can't get things to work either. Sorry, I honestly thought I had taken care of this, but now it's just something I have no idea why it's happening and how to fix it...

**Comment by porres** [comment] 2018-07-23 22:20
hmm, interesting, we may have a clue here :) - thanks

**Comment by porres** [comment] 2018-11-01 05:14
Hi @reduzent - I added "closedir" with https://github.com/porres/pd-else/commit/92b4431173b0cf294fa5011c62c951d718ed43c8

see if this helps you... but I can see this has nothing to do with the crash @LGoodacre is getting, his test patch still crashes.

Can you compile the code and test? and also check if the "lsof" thing still reports the same? thanks

**Comment by reduzent** [comment] 2018-11-22 13:51
Hi @porres 

I tested with the most current version of else (c919dd51) and it seems [dir] is still leaking file handles. On each iteration of sending [reset, open .( to [dir], it leaks one handle, as I can see it in the output of `lsof -c pd`. Previously, it leaked three handles per iteration, so there is some improvement, but the issue doesn't look fixed to me. Pd will just crash later than before.

**Comment by porres** [comment] 2019-02-08 16:07
Ok, so Claude says the leak seems to be on this line: https://github.com/porres/pd-else/blob/9b259f24569a13069c5842ec0f598e8fe96c8cbc/Classes/Source/dir.c#L75

And that I must keep the return value of opendir and close it when no longer needed.

At first glance, I don't know what this means, but I'l keep looking at it, haha...

**Comment by porres** [comment] 2019-02-08 17:52
> But I tested the same patch with [ggee/getdir] and [moocow/readdir] and both seemed to be fine until 10,000 instances, with no unexpected behavior.

moocow/readdir will also crash Pd, not when instantiating, but if you ask all instances to open a directory. It seems the issue is inherent to the <dirent.h> dependency both [readdir] and [dir] use! It doesn't seem to handle "too many open" directories... so whenever we open a directory in such circumstance, it needs to be closed right away. This is how I was able to prevent this patch from crashing, but it's bad for the design of this object, where I wanted it to leave the directory open so we could keep querying for files without the need to reopen every time. 

I guess I can just deal with this by opening/closing all the time, but it kinda sucks...

Anyway, if you read http://pubs.opengroup.org/onlinepubs/7908799/xsh/opendir.html you can see that it says "**applications will only be able to open up to a total of {OPEN_MAX} files and directories**", and this is what I believe is screwing things up... and there doesn't seem to be anything to be done here...

I could also try and see how other Pd objects deal with this... I'm using dir to remove my dependency of [playlist], haven't tested how it'd behave in this situation, probably fine. I have tested [hcs/folder_list] though, it does this sort of thing and doesn't seem to crash!

**Closed** 2019-02-08 18:54 UTC
Labels: Beta 17, bug

**Comment by porres** [comment] 2019-02-08 18:56
yeah, so, I seem to have fixed this by dealing with the fact I need to open and close every single time! no big deal in the end, I just removed the "close" message because it's not needed anymore... sorry it took me so long to figure this out!

**Comment by reduzent** [comment] 2019-05-05 15:45
I'm afraid the bug isn't fixed. [dir] still leaks file handles. However, the process to trigger the leak is a bit different:

```
[reset, open ., dump(
|
[dir ]
```
It seems one file handle doesn't get properly closed when doing the above, as can seen with 

```
lsof -c pd | wc -l 
```
Each iteration leaks exactly one handle.
