### ISSUE TITLE
[shaper~] makes Pd crash when DSP is on

### ISSUE THREAD

**Issue by bazilmuzik** [porres/pd-else#1177] opened 2022-02-06 15:25 UTC
I have nothing to really add there... You can see the problem with the help file... As soon as you put the DSP on, e.g. by raising the volume of [out~], Pd freezes and can only be left with the Task Manager (at least that's how the problem manifests itself on Windows).

Here are my specifications:

Prozessor	Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz   2.50 GHz
Installierter RAM	4,00 GB (3,89 GB verwendbar)
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

Edition	Windows 10 Pro
Version	21H2
Betriebssystembuild	19044.1466
Leistung	Windows Feature Experience Pack 120.2212.3920.0

Pd version: 0.52-1
ELSE version: 1.0-0 beta-45
architecture: AMD64

**Comment by porres** [comment] 2022-02-06 16:00
can't reproduce this on my machine, need more info on your system...

**Comment by bazilmuzik** [comment] 2022-02-06 16:39
Here are my specifications:

Prozessor	Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz   2.50 GHz
Installierter RAM	4,00 GB (3,89 GB verwendbar)
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

Edition	Windows 10 Pro
Version	21H2
Betriebssystembuild	19044.1466
Leistung	Windows Feature Experience Pack 120.2212.3920.0

**Comment by porres** [comment] 2022-02-06 21:21
I need your OS info, Pd version, ELSE version... but it's hard for me to fix this since I don't use windows and can't see the problem.

**Comment by bazilmuzik** [comment] 2022-02-07 00:19
OS : I'm on Windows 10... is that the answer ? Sry, I'm not really clear about that concept
Pd version: 0.52-1
ELSE version: 1.0-0 beta-45

**Comment by porres** [comment] 2022-02-07 00:35
can you test if lyonpotpourri/waveshape~ works for you?

**Comment by bazilmuzik** [comment] 2022-02-08 15:16
Just out of curiosity, I opened some of the other [shaper~] files with Notepad (shaper~.d_fat, shaper~.l_amd64, etc.).

In shaper~.m_i386, I found this error messages:

buffer_redraw 1 
buffer_redraw 2 
no such array '%s' (or '0-%s')
Address %p has no image-section
VirtualQuery failed for %d bytes at address %p
Unknown pseudo relocation bit size %d
cos
Unknown error
_matherr(): %s in %s(%g, %g)  (retval=%g)
Argument domain error (DOMAIN)
Argument singularity (SIGN)
Overflow range error (OVERFLOW)

Maybe that has something to do with the problem ?

**Comment by bazilmuzik** [comment] 2022-02-08 18:14
Notepad++ is a device on Windows that allow you to open any type of file to see a bit what's inside it (but not perfectly depending on the source code, it can have problems in interpreting symbols). E.g. if I open a Pd patch with Notepad++ I can see the crude Pure Data code (you know, with #N, obj, connect, etc., all the raw commands). 
But yeah, I haven't any knowledge in what binaries do what... I checked shaper~.m_amd64, and I find this message, between a whole mess of strange character:

buffer_redraw 1
buffer_redraw 2
no such array '%s' (or '0-%s')
Mingw-w64 runtime failure:
Address %p has no image-section
VirtualProtect failed with code 0x%x
Unknown pseudo relocation protocol version %d.
Unknown pseudo relocation bit size %d.
Argument domain error (DOMAIN)
Argument singularity (SIGN)
Overflow range error (OVERFLOW)
Partial loss of significance (PLOSS)
Total loss of significance (TLOSS)
The result is too small to be represented (UNDERFLOW)
Unknown error
_matherr(): %s in %s(%g, %g)  (retval=%g)

**Comment by bazilmuzik** [comment] 2022-02-08 18:16
I just need to add that the messages I copied are probably not the full messages, as I get things like NUL and strange characters all over the place, I'm just copying the places where things make sense :)

**Comment by porres** [comment] 2022-02-08 18:17
wow... hahaha, well, notepad doesn't seem to be a useful debugging option then, just tell me if you system's architecture is "amd64 (Intel/AMD 64bit)"

**Comment by porres** [comment] 2022-02-09 15:09
> how can I know my system architecture ?

deken knows if you don't

**Comment by bazilmuzik** [comment] 2022-02-09 17:59
Oh, never mind... Deken downloads everything for ELSE, but I tried [vstplugin~] and there it only proposed AMD64, so I guess that's it :)

**Comment by porres** [comment] 2022-04-21 02:15
@Lucarda, can you help me with this one? Does it crash for you?

**Comment by Lucarda** [comment] 2022-04-21 12:51
Yes it does crash here.

Here's the debugger:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffe29d01593 in shaper_perform (w=0x28db477f9d8) at Classes/Source/shaper~.c:124
124                 output = x->x_cheby[i];
```

**Comment by porres** [comment] 2022-04-21 17:09
where can I get that debuuger? would be nice to pass all object thought it :)

**Comment by porres** [comment] 2022-04-21 17:24
Ok @Lucarda , can you try now the debugger here to see if it is fixed? https://github.com/porres/pd-else/commit/ca640238b7c6fd922ab959ff415cfa166556757f

I got some of the stuff in here from lyonpotpourri's waveshape~ which @bazilmuzik  says works just fine, but we can also maybe test a debugger on it as well? See https://github.com/pd-projects/lyonpotpourri/blob/master/waveshape~.c

**Comment by Lucarda** [comment] 2022-04-21 18:06
let's put away lyonpotpourri's waveshape~ for now.

ca64023 got worse. It also hangs gdb.

sidenote:

this is the first time i tried to `clone` else but I can't. This is what I get:

```
$ git clone https://github.com/porres/pd-else.git
Cloning into 'pd-else'...
...
error: filename in tree entry contains backslash: 'clock~ imp~ on:off\.pd'
fatal: Not all child objects of ceb316f39621d3a5512db78289d0494fb0749f3c are reachable
fatal: index-pack failed
```

**Comment by porres** [comment] 2022-04-21 18:26
> filename in tree entry contains backslash:

yikes, and where the hell is 'clock~ imp~ on:off\.pd'????

**Comment by porres** [comment] 2022-04-21 18:27
> https://github.com/porres/pd-else/commit/ca640238b7c6fd922ab959ff415cfa166556757f got worse. It also hangs gdb.

well, all I did was trying to make it more like waveshape~ from ericlyon :/

**Comment by Lucarda** [comment] 2022-04-21 19:16
I need to do a reboot on all this.

My gdb output from https://github.com/porres/pd-else/issues/1177#issuecomment-1105169082 I think it was from an v1.0-rc1 e65fae3 build. 

As from the git `clone` I will try to update to the latest git.

**Comment by Lucarda** [comment] 2022-04-21 19:28
I rebooted and got the latest `git` but it also fails on Windows:

```
$ git clone https://github.com/porres/pd-else.git
Cloning into 'pd-else'...
...
error: invalid path 'Live-Electronics-Tutorial/Part.06-Filters(Basic)/25-Filters.types/2.Filter.Types/1.Low:High-Pass/1.[lop~].pd'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

:(

**Comment by porres** [comment] 2022-04-21 19:31
renamed the folder, try it now

**Comment by Lucarda** [comment] 2022-04-21 19:32
:)

yep.
Working now.

**Comment by porres** [comment] 2022-04-21 19:41
so, any information on why my changes made it so worse???

**Comment by Lucarda** [comment] 2022-04-21 19:50
no, not really.

I never did any dsp external so can't tell much.

53e00123 ?

line 159 ?

**Comment by porres** [comment] 2022-04-21 19:58
https://github.com/porres/pd-else/commit/53e0012370aad488d07e1afccbecc4cb6036b0d7 ?

nope https://github.com/porres/pd-else/commit/ca640238b7c6fd922ab959ff415cfa166556757f

> line 159 ? 

if you don;t know, then I don't :) 

I can revert back to the state from the release of rc1 and just try to set x_cheby/x_coef as 'float' instead of 't_float'. this was my guess.

**Comment by porres** [comment] 2022-04-21 20:02
> I can revert back to the state from the release of rc1 and just try to set x_cheby/x_coef as 'float' instead of 't_float'. this was my guess.

ok here it is --> https://github.com/porres/pd-else/commit/214ceeb3f391cff688812a83eb2d4227b6dc7c1b

please try the debuuger now

**Comment by Lucarda** [comment] 2022-04-21 20:11
No output from the debugger. Pd just hangs when turning on DSP.

**Comment by porres** [comment] 2022-04-21 20:15
damn... so we have no clue on what might be wrong... and are you trying a patch just with a single [shaper~] object?

I guess I'll have to redo this from scratch and merge lyon's waveshape~ and cyclone/lookup~ again...

**Comment by Lucarda** [comment] 2022-04-21 20:16
please wait. I might be doing something wrong. I should have got the same output as my first one, right?

**Comment by porres** [comment] 2022-04-21 20:19
> please wait. I might be doing something wrong. I should have got the same output as my first one, right?

Well, I did change the code from the first one - I did set x_cheby/x_coef as 'float' instead of 't_float' (as it was on your first one). Apparently I may have fixed the segfault, but Pd still crashes...

**Comment by porres** [comment] 2022-04-21 20:20
try changing line 14 and 15 back to 't_float' instead of 'float' to see if your first output comes back again... https://github.com/porres/pd-else/blob/master/Classes/Source/shaper~.c#L14

**Comment by Lucarda** [comment] 2022-04-21 20:27
I changed the lines but I can't get output anymore. :(

**Comment by porres** [comment] 2022-04-21 20:28
> I changed the lines but I can't get output anymore. :(

well, nothing makes sense then...

it should be the same as the code from https://github.com/porres/pd-else/releases/tag/v1.0-rc1

just for the sake of it, can you try the debugger on that release tag stage for shaper~?

**Comment by Lucarda** [comment] 2022-04-21 20:52
Oh shit :)

I can't get that output anymore.

I hate when this happens (and publicly)

Not really sure when I got the first one. But thats the only proof I got. 

Will investigate more if I can.

**Comment by Lucarda** [comment] 2022-04-21 23:22
I got lost on this one.

I can get gdb output if I comment out some stuff but not about what we are looking for: the freeze.

Let me know when there's something new to test.

**Comment by porres** [comment] 2022-04-22 01:22
damn, that was weird... anyway, can you help me figuring out and using debuggers? would be nice to run it through all my files

**Comment by Lucarda** [comment] 2022-04-22 02:13
### alldebug

compile `else` with

`make alldebug`

this exports all debug symbols to the dlls. never use the `install` target as it strips the debug symbols. You might need to copy the new big sized dlls to your `else` testing dir (I use the normal documents/pd/externals/else (with all the help patches and stuff).

### msys2

On your msys2 installation open the **msys** shell and do (-Ss flag searches):

`pacman -Ss gdb`

it will list different gdb's for different compilers. In my case I installed the one for the compiler i use (-S flag installs):

`pacman -S mingw64/mingw-w64-x86_64-gdb` 



----------

To use it you must start Pd inside the **mingw x64** shell:

start the mingw shell and `cd` to `<your-pd-installation>/bin`

with the shell on the `bin` dir do:

```
> gdb --args pd [cmd line args if needed ...]
> run
```

use Pd normally. When you get a crash it will be (hopefully) reported to the mingw shell.

you can type `bt` and press enter (as many times you need) to get more info.

### macOS

IIRC on macOS is roughly the same but it's called `lldb` (i think it comes already installed with xcode)

open Pd's `bin` folder on a terminal and run like:

https://lldb.llvm.org/use/map.html

can't remember how I did it some months ago.

**Comment by Lucarda** [comment] 2022-04-23 07:39
I'm totally happy :)

I found it!

`int n = (int)(w[4]);` to line 107

I'm not sure if I will be able to compile this weekend. May be you want to roll back shaper~ to c6c66a29b. I can't go back on my Windows Git because of the incompatible filenames prior to a856a53fa44

**Comment by porres** [comment] 2022-04-23 16:50
> int n = (int)(w[4]); to line 107

which file has this? the current one in repo has "t_int n = w[4];" instead.

"t_int n = w[4];" by the way is how waveshape~.c from eric lyon is coded and that one seems to work! Can you also test that one? I think it is important to run it through a debugger and see if crashes. If not, then I need to copy it.

**Comment by Lucarda** [comment] 2022-04-25 06:28
> "t_int n = w[4];" by the way is how waveshape~.c from eric lyon is coded and that one seems to work!

no, is the other way round: https://github.com/ericlyon/pd-lyonpotpourri/blob/master/waveshape~.c#L139

`t_int n = w[4];` is what freezes Windows.

**Comment by porres** [comment] 2022-04-25 08:48
i can try changing but how come doesn't waveshape~ blow up pd?

**Comment by porres** [comment] 2022-04-25 08:52
try https://github.com/porres/pd-else/commit/2d387e49fe779195e9d667cd600f1078930c0ec5

**Comment by Lucarda** [comment] 2022-04-25 10:19
> try https://github.com/porres/pd-else/commit/2d387e49fe779195e9d667cd600f1078930c0ec5

Nice, it worked.

but I had to delete all (at the end of the file) :https://github.com/porres/pd-else/blob/master/Classes/Source/shaper~.c#L238-L250


Seems this issue can be closed.

**Comment by porres** [comment] 2022-04-25 14:02
thanks man, you really helped here :) how did you find it? why doesn't waveshape~ crash? I will only close if you answer me that :) since we're helping erico lyon with his stuff, let's investigate that

**Comment by Lucarda** [comment] 2022-04-25 15:06
> how did you find it?

I'm still scratching my head about the first and "only" debugger output. I'm not joking and you know it.

Without being able to get debugger info (which make me feel really angry) I didn't know where to start but obviously it was something on the DSP thing (which is totally unknown to me).

While searching for something unusual (compared to the other objects~) I changed that and voilà. It was not the first thing I tried (I also took a look from [here](https://github.com/pure-data/externals-howto#id45)). I was expecting something of that kind as the object worked Ok on my Linux machine and also on your Mac (and I wouldn't be much surprised if Windows7 users did't get the freeze/crash).

>   why doesn't waveshape~ crash? I will only close if you answer me that :) since we're helping erico lyon with his stuff, let's investigate that

eric's `waveshape~` has the `int` and then the cast `(int)(w[4])` (same as the now fixed `shaper~`) and that is working fine. Or I'm missing something?

**Closed** 2022-04-25 15:34 UTC
Labels: bug

**Comment by porres** [comment] 2022-04-25 17:14
I can swear I downloaded waveshape and it had the same thing, at least I have the code here... I can swear, but apparently I'm just completely crazy and psychotic and need to enter a mental institution, which is not a nice feeling

**Comment by Lucarda** [comment] 2022-04-26 05:13
:)

If people around you ask you to jump in the hospital, give up and do as they say. Let the doctors do their job.

I'm under expensive treatment since 2000 and spend 6 months in a hospital back in 2006. The hospital was not bad, nice food and new exotic companions. :)

I'm currently renewing my official papers that allows my mother to get money from the state to cover my needs.

paranoid schizophrenia

:)

PS: My doctor sees with good eyes that I'm spending so much time learning and helping with Pd-dev(s). I'm 47 this year.
