### ISSUE TITLE
Error when using keyboard in zoom 

### ISSUE THREAD

**Issue by charlesneimog** [porres/pd-else#1618] opened 2023-04-22 15:37 UTC
Hi, I'm having some errors when I use the `keyboard` with zoom. 

It doesn't draw things in the right place, as well as not being able to select (the selectable size works when I'm not zoomed in).

![Kooha-2023-04-22-12-33-20](https://user-images.githubusercontent.com/31707161/233793593-038fad3b-c587-4426-8570-7e00748be434.gif)

**Comment by porres** [comment] 2023-04-22 15:42
duplicate of https://github.com/porres/pd-else/issues/1395

**Closed by porres** 2023-04-22 15:42 UTC
